### ISSUE TITLE
Did you have an idea why this error accure with PIP

### ISSUE THREAD

**Issue by mrhili** [leokhoa/laragon#104]
C:\laragon\www\learnlv2
λ python --version
Python 3.6.1

C:\laragon\www\learnlv2
λ pip freeze
Traceback (most recent call last):
  File "C:\laragon\bin\python\python-3.6.1\Scripts\\__pip__.py", line 5, in <module>
    from pip import main
  File "C:\laragon\bin\python\python-3.6.1\lib\site-packages\pip\__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "C:\laragon\bin\python\python-3.6.1\lib\site-packages\pip\_vendor\requests\__init__.py", line 65, in <module>
    from . import utils
  File "C:\laragon\bin\python\python-3.6.1\lib\site-packages\pip\_vendor\requests\utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "C:\laragon\bin\python\python-3.6.1\lib\site-packages\pip\_vendor\requests\compat.py", line 60, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
OSError: [Errno 9] Bad file descriptor

**Comment by alxndr-w** [comment]
Unfortunately, this issue is now 5 years old an nobody else experienced the same problem or offered a solution. That's why I'll close this issue for now.
