### ISSUE TITLE
Error: ImagickException: NonconformingDrawingPrimitiveDefinition

### ISSUE THREAD

**Issue by josuechevez1998** [leokhoa/laragon#873]
I need help 
`
ImagickException: NonconformingDrawingPrimitiveDefinition `6' @ error/draw.c/RenderMVGContent/4466 in C:\laragon\www\ssuees\vendor\bacon\bacon-qr-code\src\Renderer\Image\ImagickImageBackEnd.php:168 Stack trace: #0 C:\laragon\www\ssuees\vendor\bacon\bacon-qr-code\src\Renderer\Image\ImagickImageBackEnd.php(168): Imagick->drawImage(Object(ImagickDraw)) #1 C:\laragon\www\ssuees\vendor\bacon\bacon-qr-code\src\Renderer\ImageRenderer.php(72): BaconQrCode\Renderer\Image\ImagickImageBackEnd->done() #2 C:\laragon\www\ssuees\vendor\bacon\bacon-qr-code\src\Writer.php(54): BaconQrCode\Renderer\ImageRenderer->render(Object(BaconQrCode\Encoder\QrCode)) #3 C:\laragon\www\ssuees\vendor\simplesoftwareio\simple-qrcode\src\Generator.php(171): BaconQrCode\Writer->writeString('http://ssuees.d...', 'ISO-8859-1', Object(BaconQrCode\Common\ErrorCorrectionLevel)) #4 C:\laragon\www\ssuees\app\Mail\ResdMail.php(42): SimpleSoftwareIO\QrCode\Generator->generate('http://ssuees.d...', 'C:\\laragon\\www\\...') #5 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Mail\Mailable.php(1656): App\Mail\ResdMail->content() #6 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Mail\Mailable.php(1573): Illuminate\Mail\Mailable->ensureContentIsHydrated() #7 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Mail\Mailable.php(198): Illuminate\Mail\Mailable->prepareMailableForDelivery() #8 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Support\Traits\Localizable.php(19): Illuminate\Mail\Mailable->Illuminate\Mail\{closure}() #9 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Mail\Mailable.php(197): Illuminate\Mail\Mailable->withLocale(NULL, Object(Closure)) #10 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(309): Illuminate\Mail\Mailable->send(Object(Illuminate\Mail\Mailer)) #11 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(253): Illuminate\Mail\Mailer->sendMailable(Object(App\Mail\ResdMail)) #12 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Mail\PendingMail.php(124): Illuminate\Mail\Mailer->send(Object(App\Mail\ResdMail)) #13 C:\laragon\www\ssuees\app\Http\Controllers\Resd\FacturaController.php(177): Illuminate\Mail\PendingMail->send(Object(App\Mail\ResdMail)) #14 C:\laragon\www\ssuees\app\Http\Controllers\Resd\FacturaController.php(48): App\Http\Controllers\Resd\FacturaController->enviarCorreoAprobacion(Object(App\Models\ResdSolicitudesEspaciosDeportivo)) #15 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\Resd\FacturaController->confirmarPago(Object(App\Models\ResdSolicitudesEspaciosDeportivo), Object(Illuminate\Http\Request)) #16 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('confirmarPago', Array) #17 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Routing\Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Resd\FacturaController), 'confirmarPago') #18 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController() #19 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Routing\Router.php(798): Illuminate\Routing\Route->run() #20 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #21 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #22 C:\laragon\www\ssuees\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #23
`

**Comment by alxndr-w** [comment]
I'm sorry, but this isn't Laragon related. Check out this stackoverflow discussion: <https://stackoverflow.com/questions/57456197/imagemagick-non-conforming-drawing-primitive-definition-px>
